version: 3

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - odin build src/game -out=bin/main.exe
    aliases:
      - b
    # silent: true
    sources:
      - ./src/**/*.odin
    generates:
      - bin/main.exe
      
  build_run:
    cmds:
      - odin run src/game -out=bin/main.exe
    aliases:
      - br
    # silent: true
    sources:
      - ./src/**/*.odin
    generates:
      - bin/main.exe

  run:
    cmds:
      - ./bin/main.exe
    aliases:
      - r

  check:
    cmds:
      - powershell -Command "& odin_check"
    aliases:
      - c  
